#+TITLE: Helpful Scripts and dotfiles
#+AUTHOR: Óscar Nájera

* Emacs Configuration
My current configuration for everyday use.

It uses an [[http://orgmode.org/][Orgmode]] file for structure which is then converted into
Emacs lisp code as Emacs starts. Package installation relies on
[[https://github.com/jwiegley/use-package][use-package]].
* Automatizing
* Keyboard Layout
After putting so much time in front of a computer with keyboards as the
for the moment most practical way of inputting my ideas to it I started
to put attention to this process.

I started with an arbitrary personal mix of the English Programmers
Dvorak Keyboard layout. It served me well for a long time, but it is
not enough. Its based on written text, but there is more to the
computing experience that final text we produce. There are
keybindings, commands inputs which I started to care about.

I keep statistics of my key presses(Computer does it, very reliable)
and my overall comfort(very biased). Now I iteratively develop upon
new key-layouts. Huge pain every change as my brain has to re-adapt to
the new keys every time, but I feel now something is coming out of it.

I also start to see that getting a more hand shaped keyboard could help
a lot. All this tilted key columns are just bad.
* Installing in foreign computers
Getting to work with a computing cluster is a pain. Not all my
packages are available. I'm no HPC expert, but I'm getting forward
into getting my work to execute on those nodes.

See [[file:localinstall.sh][Local package manager]]
* Fonts
I use nerd-fonts from AUR
#+BEGIN_SRC bash
  yaourt nerd-fonts-complete
#+END_SRC
* Change dates in images
Using exiftool I can change/shift the date information of a foto. This is
helpful since I forget to update the camera clock.
#+BEGIN_SRC sh
#                    Y:MM:DD HH:M:S
exiftool "-alldates+=6:11:12 14:0:0" photo.jpg
#+END_SRC
